repos:
  # Run pytest to ensure all tests pass before committing
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run python -m pytest
        language: system
        pass_filenames: false
        files: \.py$
        description: "Run pytest to ensure all tests pass"

  # Standard pre-commit hooks for code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements

  # Ruff - The complete Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        files: \.py$
      # Run the formatter
      - id: ruff-format
        files: \.py$
