name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Add uv to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Sync dependencies (prod + dev)
      run: |
        uv sync --dev

    - name: Run unit tests (skip e2e)
      run: |
        uv run python -m pytest -q -m 'not e2e'

  e2e:
    runs-on: ubuntu-latest
    needs: unit
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Add uv to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Sync dependencies (prod + dev)
      run: |
        uv sync --dev

    - name: Run E2E tests
      env:
        STREAMLIT_HEADLESS: 'true'
      run: |
        uv run python -m pytest -q -m e2e
